### ISSUE TITLE
0.11.0: ParseIntError { kind: InvalidDigit } 

### ISSUE THREAD

**Issue by dholroyd** [iai-callgrind/iai-callgrind#161]
On upgrading from 0.10.2 to 0.11.0 in CI, the [job fails](https://github.com/dholroyd/mpeg2ts-reader/actions/runs/9013456523/job/24764312629?pr=60) with,

```
thread 'main' panicked at iai-callgrind-runner/src/runner/mod.rs:116:10:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
```

**Comment by dholroyd** [comment]
Ah, I need to update iai-callgrind-runner too.

**Comment by gamma0987** [comment]
Thanks for reporting. Yeah, the error message isn't clear about what's going on.

You need to update the `iai-callgrind-runner` binary, too. In the ci step before just exchange `cargo binstall iai-callgrind-runner@0.10.2` with `cargo binstall iai-callgrind-runner@0.11.0`

To automate this step in the ci, there's an example in the `README`:

```yaml
- name: Install iai-callgrind-runner
  run: |
    version=$(cargo metadata --format-version=1 |\
      jq '.packages[] | select(.name == "iai-callgrind").version' |\
      tr -d '"'
    )
    cargo binstall iai-callgrind-runner --version $version
```
