### ISSUE TITLE
[Far future] Add support for DHAT and maybe Massif?

### ISSUE THREAD

**Issue by mohe2015** [iai-callgrind/iai-callgrind#18]
I don't know if you would ever want to do this (or want a contribution in that direction) but it seems like this would be a great addition to this tool. I don't know though if it is even possible to add this nicely or if the way the instrumentation works would be largely different.

**Comment by gamma0987** [comment]
I've finished this feature and running additional valgrind tools for benchmarks is going be supported in the upcoming release. In addition to DHAT and Massif it's also possible to run Memcheck, Helgrind, DRD and the experimental BBV. The output files of the profiling tools are placed next to the callgrind output files in `target/iai` ready to be examined with `dh_view.html`, `ms_print` and alike. If you wish to see the logging output of these tools you can run the benchmarks with the environment variable `IAI_CALLGRIND_LOG=info`. If there is something missing, wrong or you have questions, feel free to reopen this issue or create a new one.
