### ISSUE TITLE
request: packaging `dh_view` with the runner

### ISSUE THREAD

**Issue by OmarTawfik** [iai-callgrind/iai-callgrind#196]
Currently, to visualize DHAT output, we need to download a Valgrind release from https://valgrind.org/downloads/ and open the included `dhat/dh_view.html` to load/visualize them. However, this can lead to issues as `iai-callgrind` releases/features don't match up with Valgrind release cadence, leading to versioning issues.

I suggest packaging/releasing the `dhat/dh_view.html` tool with the `iai-callgrind-runner` crate that contains the DHAT tool runner, so that they are always accurate.

**Comment by gamma0987** [comment]
I'm sorry, but I don't think this is a good idea. `iai-callgrind` is intentionally independent from valgrind versions. Which distro are you using? `dh_view.html` should be packaged with valgrind. For example debian/ubuntu and arch linux include it.

**Comment by OmarTawfik** [comment]
I was under the impression that `dhat` output from `iai_callgrind` is different/modified than the one bundled with `valgrind`, but after digging into it, I realized it is not the case, and the output is purely controlled by the local `valgrind` installation.
Apologies for the confusion. I will close this issue.
