### ISSUE TITLE
`iai-callgrind-runner` broken incremental build

### ISSUE THREAD

**Issue by OmarTawfik** [iai-callgrind/iai-callgrind#260]
Installing this crate via the command below succeeds, but breaks cargo incrementability:

```sh
cargo install iai-callgrind-runner --version 0.12.3
```

Rerunning this command will recompile the binary from scratch, instead of being no-op.
This results in much slower builds, and not reusing the cache.

Expected:

```
Ignored package `iai-callgrind-runner v0.12.3` is already installed, use --force to override
```

Actual:

```log
Replaced package `iai-callgrind-runner v0.12.3` with `iai-callgrind-runner v0.12.3` (executable `iai-callgrind-runner`)
```

**Comment by gamma0987** [comment]
Strange. Thanks for reporting this. I could reproduce it but don't know why this is happening, yet. Can you use `binstall`? Using `cargo binstall iai-callgrind-runner@0.12.3` seems to work:

```
❯ cargo binstall iai-callgrind-runner@0.12.3
 INFO iai-callgrind-runner v0.12.3 is already installed, use --force to override
 INFO Done in 1.242239ms
```

**Comment by gamma0987** [comment]
It looks like a cargo issue: https://github.com/rust-lang/cargo/issues/8703

`iai-callgrind-runner` is behind a feature gate and `schema-gen` which we only use internally, too.

**Comment by OmarTawfik** [comment]
Thanks for looking into this!

**Comment by gamma0987** [comment]
The fix will be part of the next release, but that doesn't fix the issue for older releases. For older releases `binstall` can be used to circumvent the problem with `cargo install`.

**Comment by gamma0987** [comment]
Does this solve your issue?

**Comment by OmarTawfik** [comment]
Yes. Thank you!
