### ISSUE TITLE
Unmaintained dependency on proc-macro-error

### ISSUE THREAD

**Issue by GumpacG** [iai-callgrind/iai-callgrind#262]
Are there plans to update `proc-macro-error` to `proc-macro-error2`? If so, is there an ETC for this update?

I've recently gotten this error:
```
proc-macro-error 1.0.4 registry+https://github.com/rust-lang/crates.io-index
    │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
```

**Comment by acarbonetto** [comment]
seems related to https://github.com/iai-callgrind/iai-callgrind/pull/78

**Comment by gamma0987** [comment]
Yes #78 is related but was never finished by the author. But, the usage of proc-macro2-diagnostics is not as nice as proc-macro-error. [proc-macro-error2](https://github.com/GnomedDev/proc-macro-error-2) looks promising. I'll try migrating the next days.
