### ISSUE TITLE
Add support for comparing against a baseline instead of old output

### ISSUE THREAD

**Issue by gamma0987** [iai-callgrind/iai-callgrind#29]
The basic idea is to run the benchmarks once in baseline mode and then compare benchmark runs between new vs. base instead of new vs. old. I actually like how `criterion.rs` is doing it, but instead of using command line arguments (which are currently reserved for callgrind arguments) we could use environment variables. Environment variables have the additional benefit, that it's possible to run multiple benchmarks in one go instead of just one benchmark with `--bench $BENCHMARK_NAME -- --save-baseline=...` (Running `cargo bench -- --save-baseline=...` usually fails even before the iai-callgrind benchmark harness is reached).

Maybe something like this:

* `IAI_CALLGRIND_SAVE_BASELINE=$NAME`: Compare against this baseline if present and then overwrite it
* `IAI_CALLGRIND_BASELINE=$NAME`: same as above but without overwriting
* `IAI_CALLGRIND_LOAD_BASELINE=$NAME`: Load this baseline as the `new` data set instead of creating a new one

**Comment by jalil-salame** [comment]
On the same vein: compare against function.

```rust
#[library_benchmark]
#[bench:size_10(generate(10))]
#[bench:size_1000(generate(1000))]
fn linear(nums: &[i32], target: i32) { ... }


#[library_benchmark]
#[bench:size_10(generate(10))]
#[bench:size_1000(generate(1000))]
fn binary(nums: &[i32], target: i32) { ... }

compare_group!(linear, binary);
```

Then you get a comparison between `binary::size_10` and `linear::size_10`, and `binary::size_1000` and `linear::size_1000`.

**Comment by gamma0987** [comment]
I like the basic idea. But, I'm not sure about the `compare_group` macro and how to integrate this nicely. If possible, I would rather like to use the LibraryBenchmarkConfig. Maybe in a `LibraryBenchmarkConfig::baseline` method in which you could specify an enum with different modes like Baseline::Old to compare against the old output as usual, a Baseline::Bench("function_name", Some("id")), ... other modes.

However, one thing after another, so I would first concentrate on the originally proposed baseline mode. Maybe, you could move this into a new issue?

**Comment by jalil-salame** [comment]
> I like the basic idea. But, I'm not sure about the `compare_group` macro and how to integrate this nicely. If possible, I would rather like to use the LibraryBenchmarkConfig. Maybe in a `LibraryBenchmarkConfig::baseline` method in which you could specify an enum with different modes like Baseline::Old to compare against the old output as usual, a Baseline::Bench("function_name", Some("id")), ... other modes.
> 
> However, one thing after another, so I would first concentrate on the originally proposed baseline mode. Maybe, you could move this into a new issue?

Will do!
