### ISSUE TITLE
library_benchmark_group! is private

### ISSUE THREAD

**Issue by ryanpeach** [iai-callgrind/iai-callgrind#298]
https://github.com/iai-callgrind/iai-callgrind/blob/25f9270b56d3e94ef05ca027c9cc2c3e8d83a8aa/iai-callgrind/src/macros.rs#L1429

```
error[E0603]: module `xyz_group` is private
  --> benches/bench_main.rs:6:56
   |
6  | use crate::...::xyz_group;
   |                  ^^^^^^^^ private module
   |
note: the module `xyz_group` is defined here
  --> benches/.../xyz.rs:81:1
   |
81 | / library_benchmark_group!(
82 | |   name=xyz_group;
83 | |   benchmarks =
84 | |     bench_xyz
85 | | );
   | |_^
   = note: this error originates in the macro `library_benchmark_group` (in Nightly builds, run with -Z macro-backtrace for more info)
```

How can we make large structured `benches/` folders with `benches/bench_main.rs` entrypoints if the macros export private modules?

Basically I have:

```
- benches
  - bench_main.rs
  - folder
    - ...
      - xyz.mod
```

with a library_benchmark_group! in it.

**Comment by gamma0987** [comment]
This looks like an error to me. The mod https://github.com/iai-callgrind/iai-callgrind/blob/25f9270b56d3e94ef05ca027c9cc2c3e8d83a8aa/iai-callgrind/src/macros.rs#L1429 you pointed out should be `pub`.

**Comment by ryanpeach** [comment]
Should I put in a PR?

**Comment by gamma0987** [comment]
Gladly

**Comment by ryanpeach** [comment]
https://github.com/iai-callgrind/iai-callgrind/pull/300

**Comment by gamma0987** [comment]
Closing this as completed with #300
