### ISSUE TITLE
Question: Reducing sample count

### ISSUE THREAD

**Issue by ryanpeach** [iai-callgrind/iai-callgrind#307]
> Unable to complete 100 samples in 5.0s. You may wish to increase target time to or reduce sample count to 10.

How does one do that? I can't find it in the documentation.

**Comment by gamma0987** [comment]
Sorry, can you please elaborate?

**Comment by ryanpeach** [comment]
This was a warning I got while benchmarking a rather slow function. It may be from valgrind or callgrind itself. But I can't find an option in valgrind/callgrind which sets a sample count like it suggests.

**Comment by gamma0987** [comment]
This isn't a warning from valgrind or iai-callgrind but from criterion.

**Comment by gamma0987** [comment]
I'm closing this as unrelated to iai-callgrind
