### ISSUE TITLE
Compare functions in group (follow up to #29)

### ISSUE THREAD

**Issue by jalil-salame** [iai-callgrind/iai-callgrind#37]
One of the features I miss from cirterion is [comparing functions](https://bheisler.github.io/criterion.rs/book/user_guide/comparing_functions.html) (follow link to see how they do it).

This could be added to the existing `library_benchmark_group!`, by having functions with different names but same id automatically compare against each other:

```rust
#[library_benchmark]
#[bench:size_10(generate(10))]
#[bench:size_1000(generate(1000))]
fn linear(nums: &[i32], target: i32) { ... }


#[library_benchmark]
#[bench:size_10(generate(10))]
#[bench:size_1000(generate(1000))]
fn binary(nums: &[i32], target: i32) { ... }

library_benchmark_group!(
    name = search;
    // Maybe you need to add something to the LibraryBenchmarkConfig to make this work
    benches = linear, binary
);
```

It is interesting to compare both `size_10::linear` to `size_10::binary` and `size_10::linear` to `size_1000::linear`. So maybe have an option to configure that?

**Comment by gamma0987** [comment]
Thanks for moving this into a separate issue. I like it especially

> by having functions with different names but same id automatically compare against each other

> // Maybe you need to add something to the LibraryBenchmarkConfig to make this work

I think `compare_benches = true;` in a `library_benchmark_group!` could be sufficient.
