### ISSUE TITLE
 Support hiding all of cache-related metrics

### ISSUE THREAD

**Issue by ryoqun** [iai-callgrind/iai-callgrind#94]
Callgrind's close-kin, Callgrind recently (`Release 3.21.0 (28 Apr 2023)` and onwards) changed its default to `--cache-sim=no`, alluding its dubious relevance as to recent cpus in the changelog (https://valgrind.org/docs/manual/dist.news.html):

```
* Cachegrind:
  - `--cache-sim=no` is now the default. The cache simulation is old and
    unlikely to match any real modern machine. This means only the `Ir`
    event are gathered by default, but that is by far the most useful
    event.
```

I think this is true and applicable to `Callgrind`. On top of it, `Callgrind`'s `--cache-sim` default is `no` already.

That said, I'd like to have some cli flag to opt-out showing cache-related metrics altogether like this (so that to avoid `iai-callgrind`'s default behavior):

```
test_lib_bench_readme_example_fibonacci::bench_fibonacci_group::bench_fibonacci short:10
  Instructions:                1733|N/A             (*********)
```

**Comment by gamma0987** [comment]
It's still a pr (#106) but once it's merged you can use callgrind args to turn off of the cache simulation.

Within the benchmark with the `LibraryBenchmarkConfig` (or `BinaryBenchmarkConfig`):

```rust
main!(
    config =  LibraryBenchmarkConfig::default()
        .raw_callgrind_args(["--cache-sim=no"]);
    library_benchmark_groups = my_bench
);
```

in the cli with environment variables

```shell
IAI_CALLGRIND_CALLGRIND_ARGS="--cache-sim=no" cargo bench
```

or with arguments

```shell
cargo bench --bench my_iai_benchmark -- --callgrind-args="--cache-sim=no"
```
