### ISSUE TITLE
Partially-support tracing multi-threaded bench mark code

### ISSUE THREAD

**Issue by ryoqun** [iai-callgrind/iai-callgrind#95]
Callgrind supports multi-threaded execution and measurement. However, it seems that `iai-callgrind` doesn't so.

As far as I looked into `iai-callgrind`'s code, it seems to _partially_ be possible to do so by wrapping the closure given to `std::thread::spawn` and etc like this:

```rust
use iai_callgrind::collect_current_thread;


std::thread::spawn(|| {
    collect_current_thread(|| { // this is marked as `inline[never]` and make the callgrind output collector recognize this symbol name.
        // maybe start instrumentation is on by default for compat with current behavior
        // then, users are free to enable/disable it with client requests.
    })
});

```

I wonder this feature was wanted before. and it could be ever merged if i create a pr? Note that this approach doesn't enable arbitrary thread tracing, only that the user has some control.

Considering user has full control to wrap or not any given bench-code-residing thread programmatically, I think just summarizing all metrics collected from all threads should suffice. so, no output change.

**Comment by gamma0987** [comment]
I'm not sure if I understood the issue correctly. Collection of stats from multiple threads should actually be possible with iai-callgrind, too. Or do you want to track only specific threads?

**Comment by ryoqun** [comment]
> I'm not sure if I understood the issue correctly. Collection of stats from multiple threads should actually be possible with iai-callgrind, too.

Well, I'm seeing odd results, indicating the threaded bench variant isn't tracking executions. 

Given these two identical benches other than `std::thread::spawn`, I should see almost same results (other than some thread spawning overhead). However, I'm seeing way fewer numbers from `bench_with_thread`.

```rust
#[library_benchmark]
#[bench::huge(1000000)]
fn bench_with_thread(task_count: usize) {
    std::thread::spawn(|| {
        // same heavy computing
    }).join().unwrap();
}
```

```rust
#[library_benchmark]
#[bench::huge(1000000)]
fn bench_no_thread(task_count: usize) {
    // same heavy computing
}
```

Does this work in your environment? I can share more concrete examples, if you need. For your information, I managed to see corrected results after hacking a bit around iai-callgrind's sentinel code. So, i thought my use case isn't well supported at the very least?


> Or do you want to track only specific threads?

kind of true, i want to track only specific portion of specific threads. That means, I also want to use the client requests as well (namely, `toggle_collect()`).

**Comment by gamma0987** [comment]
Your example should be enough. Yeah, looks like there might be a problem parsing the callgrind output file when using multiple threads but I'll need to take a second look. However, this may take some time since I currently don't have much time to work on `iai-callgrind`.

**Comment by gamma0987** [comment]
I've tried and I actually get the expected event counts. There's the overhead for spawning the thread in my results. You can try on your machine and checkout my test benchmark on the `95-multi-thread` branch and run it with `just bench-test test_lib_bench_multi_thread`.

I noticed you haven't returned a result from the benchmarking function. This can mislead the compiler to think it doesn't need to make the computation. Maybe it's worth a try to change your benchmark to something like that (replacing `MyResult`):

```rust
#[library_benchmark]
#[bench::huge(1000000)]
fn bench_with_thread(task_count: usize) -> MyResult {
    std::thread::spawn(|| {
        // same heavy computing
    }).join().unwrap()
}
```

**Comment by gamma0987** [comment]
Another reason for your odd results could be that you might need to make use of `std::hint::black_box`. However, you don't need the `black_box` for the input parameters (in your example the `task_count`) of the benchmark function since that's already done for you.

**Comment by gamma0987** [comment]
Can I close this? The new `0.14.0` release fully supports tracing multiple threads with and without `--separate-threads=yes`.
