### ISSUE TITLE
Provide a bump-allocator for far-less noisy results

### ISSUE THREAD

**Issue by ryoqun** [iai-callgrind/iai-callgrind#96]
Oftentimes, I'm not interested in alloc costs when micro-benching a piece of code with `iai-callgrind`. In that case, memory footprint is quite small and dealloc isn't needed for the duration of benchmark.

So, I ended up replacing `GLOBAL_ALLOCATOR` with super minimal allocator. I find the results a lot stable and reproducible.

Thus, I think providing such one as opt-in from `iai-callgrind` could be useful as well. Note there's some caveats for it and some proper doc will be needed, of course.

**Comment by gamma0987** [comment]
I'll have a look into it but I actually tend to leave such things to the final user.

**Comment by bluebear94** [comment]
> I'll have a look into it but I actually tend to leave such things to the final user.

I agree. If frequent allocations in my code are adding a lot of overhead, then I want to know about it.

**Comment by gamma0987** [comment]
Sorry, but I don't think a custom global allocator should be part of iai-callgrind. So, I'm closing this issue.
